language: php
before_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer install -n
script:
  - phpunit --coverage-clover=coverage.clover
after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - php vendor/bin/codacycoverage clover coverage.clover
php:
  - 7.0
